<a href="https://colab.research.google.com/github/DhamuSniper/Complete-guide-to-deep-learning-with-Tensorflow---Exercises/blob/master/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
print(tf.__version__)

1.14.0


In [0]:
a_var=tf.constant("hello")

In [0]:
print(a_var)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
b_var=tf.constant("world")
print(b_var)

Tensor("Const_1:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result=sess.run(a_var+b_var)

print(result)

b'helloworld'


**Interactive Session**

In [0]:
matFill= tf.fill((4,4),10)
zeroes=tf.zeros(4,4)
ones=tf.ones(4,4)
rand=tf.random.normal((4,4),mean=1, stddev=1)

In [0]:
sess=tf.InteractiveSession()

In [0]:
List=[matFill,zeroes,ones,rand]

In [0]:
for i in List:
  result=sess.run(i)
  print(result)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[0 0 0 0]
[1 1 1 1]
[[ 1.6185046   0.70866656  0.74870324  1.400517  ]
 [-0.15342307  0.48581302  0.02084225  2.6365857 ]
 [ 0.26819682  0.94577813  2.3461154   0.67806816]
 [ 0.2737276   1.1679513  -0.10935926 -0.03276539]]
